import "server-only";
import { getRuntimeConfig, serverEnvSchema } from "./runtime-config";

export { serverEnvSchema } from "./runtime-config";

// Startup validation is intentionally evaluated with the server-only module.
// `instrumentation.ts` validates it before traffic; this protects routes and
// scripts that load before instrumentation is available as well.
getRuntimeConfig();

export const serverEnv = serverEnvSchema.parse({
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  STELLAR_NETWORK_PASSPHRASE: process.env.STELLAR_NETWORK_PASSPHRASE,
  SOROBAN_RPC_URL: process.env.SOROBAN_RPC_URL,
  ATTESTATION_CONTRACT_ID: process.env.ATTESTATION_CONTRACT_ID,
  ATTESTATION_CACHE_TTL_SECONDS: process.env.ATTESTATION_CACHE_TTL_SECONDS,
  STELLAR_HORIZON_URL: process.env.STELLAR_HORIZON_URL,
  STELLAR_USDC_ISSUER: process.env.STELLAR_USDC_ISSUER,
  CHW_INCENTIVE_POOL_ADDRESS: process.env.CHW_INCENTIVE_POOL_ADDRESS,
  PAYOUT_INDEXER_START_LEDGER: process.env.PAYOUT_INDEXER_START_LEDGER,
  PAYOUT_INDEXER_START_PAYMENT_CURSOR:
    process.env.PAYOUT_INDEXER_START_PAYMENT_CURSOR,
  PAYOUT_INDEXER_CRON_SECRET: process.env.PAYOUT_INDEXER_CRON_SECRET,
  PAYOUT_INDEXER_ENABLED: process.env.PAYOUT_INDEXER_ENABLED,
  STELLAR_USDC_ASSET_CODE: process.env.STELLAR_USDC_ASSET_CODE,
  LAFIYA_DEPLOYMENT_ENV: process.env.LAFIYA_DEPLOYMENT_ENV,
  ATTESTATION_MODE: process.env.ATTESTATION_MODE,
  CHW_PROTOCOL_EPOCH_ID: process.env.CHW_PROTOCOL_EPOCH_ID,
  CHW_PROTOCOL_INTENT_SIGNING_KEY: process.env.CHW_PROTOCOL_INTENT_SIGNING_KEY,
  SENTRY_ENABLED: process.env.SENTRY_ENABLED,
  NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  SENTRY_DSN: process.env.SENTRY_DSN,
  LAFIYA_BUILD_REVISION: process.env.LAFIYA_BUILD_REVISION,
  LAFIYA_SCHEMA_COMPATIBILITY: process.env.LAFIYA_SCHEMA_COMPATIBILITY,
});
